basePath: /
definitions:
  video.ResponseSuccess:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: Fake flix API
  termsOfService: http://swagger.io/terms/
  title: Fake flix API
  version: "1.0"
paths:
  /api/v1/content/stream/{id}:
    get:
      description: Get stream content
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/video.ResponseSuccess'
      summary: Get stream content
      tags:
      - Video
  /api/v1/content/upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload a video file
      parameters:
      - description: Video file
        in: formData
        name: file
        required: true
        type: file
      - description: File name
        in: formData
        name: filename
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Upload a video file
      tags:
      - Video
swagger: "2.0"
